### ISSUE TITLE
Oval (Circle) and Arc

### ISSUE THREAD

**Issue by AndyObtiva** [gettalong/geom2d#1]
I need Oval and Arc support pronto to use in [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt/) (JRuby Desktop Development GUI Framework) if possible for Canvas graphics user interaction (knowing when a user clicked a shape with the mouse to activate it and do things with it like moving and resizing).

Thanks for making the library available in any case. I hope to see the features I asked for implemented soon. If it's not done soon enough I might use something else, but it would still be good for your library to implement them (especially since you labeled them TODO already).

Godspeed.

Andy Maleh
[Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt/) Author

**Comment by gettalong** [comment]
I'm sorry but there is currently no active development of further geom2d features due to time constraints.

**Comment by AndyObtiva** [comment]
Time constraints!? I saw you were a very very VERY active developer on [rubygems.org](https://rubygems.org/profiles/gettalong) having 66 million downloads across 23 gems. I'm sure you could dedicate some of that ruby gem time towards geom2d.

In any case, given that I use [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt/) via [JRuby](https://www.jruby.org/), I solved my problem for now by leveraging the Java built-in geometry library, which comes included for free as part of [JRuby](https://www.jruby.org/).

Still, Ruby does not have a comprehensive geometry solution as far as I can tell from rubygems. All the robust geometry gems like yours seem to glance over ovals and arcs. In the future, it could be very useful to have a comprehensive Ruby geometry gem once I implement similar features in my other library, [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) (MRI Ruby Desktop Development GUI Library). I would hope you would have that ready by then IN SPITE OF all your "time constraints".

Godspeed.

Andy Maleh

**Comment by gettalong** [comment]
If you don't understand open source/free software and time constraints, there is nothing more to say. You are free to provide a pull request for this feature if you need it "pronto".

geom2d does everything I need it for currently and I just don't have time to implement new features "just because". So I will close this issue.
